version: '3.8'

services:
  python-script:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-script-local
    volumes:
      - .:/app  # Mount the current directory for live editing
    command: python script.py  # Default command to run your script
    environment:
      - ENV=development  # Example environment variable
